# Generated by Django 3.0.4 on 2020-03-06 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='DEFAULT TITLE', max_length=50)),
                ('description', models.CharField(default='DEFAULT DESCRIPTION', max_length=500)),
                ('n_to', models.IntegerField(default=0)),
                ('s_to', models.IntegerField(default=0)),
                ('e_to', models.IntegerField(default=0)),
                ('w_to', models.IntegerField(default=0)),
                ('u_to', models.IntegerField(default=0)),
                ('d_to', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerVisited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure.Chamber')),
            ],
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='currentRoom',
            new_name='currentChamber',
        ),
        migrations.AddField(
            model_name='playervisited',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure.Player'),
        ),
    ]
