# Generated by Django 3.0.4 on 2020-03-06 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mars',
            name='grid',
        ),
    ]
