# Generated by Django 3.0.4 on 2020-03-08 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200308_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playervisited',
            old_name='room',
            new_name='chamber',
        ),
    ]
